export default [
  "Baby products",
  "Books",
  "Beauty & Personal Care",
  "Cars",
  "Cycles",
  "Clothing & Accessories",
  "Computer & Accessories",
  "Electronics",
  "Fitness",
  "Furnitures",
  "Gardens & outdoors",
  "Home appliances",
  "Iphones",
  "Kitchen products",
  "Laptops",
  "Luggage & bags",
  "Motorcycles",
  "Office products",
  "Others",
  "Phone accessories",
  "Phones",
  "Shoes",
  "Sports",
  "Smartphones",
  "Tools",
  "Toys",
  "Watches",
].sort();
