export default [
  "Beauty and personal care",
  "Books",
  "Cars",
  "Cycles",
  "Clothing and accessories",
  "Computer and accessories",
  "Electronics",
  "Fashion",
  "Fitness",
  "Furnitures",
  "Gardens and outdoors",
  "Home appliances",
  "Iphones",
  "Kitchen products",
  "Laptops",
  "Luggage and bags",
  "Motorcycles",
  "Office products",
  "Other",
  "Phone accessories",
  "Phones",
  "Properties",
  "Services",
  "Shoes",
  "Spareparts",
  "Sports",
  "Smartphones",
  "Tools",
  "Toys",
  "Watches",
].sort();
